[dependencies]
core = "2.6.1"
class-plus = "0.2.1"
icrc1-mo = "0.2.1"
icrc2-mo = "0.2.1"
icrc3-mo = "0.4.3"
icrc4-mo = "0.2.1"
timer-tool = "0.2.1"

[toolchain]
moc = "1.14.1"

[canisters.backend]
main = "backend/Backend.mo"
candid = "backend/backend.did"
